### ISSUE TITLE
[question] Performance?

### ISSUE THREAD

**Issue by tconroy** [OpenGov/react-leaflet-marker-layer#2]
I'm about to tackle a project consisting of 10,000+ data points, and will likely need to display anywhere from 1 - 500 points simultaneously, and rapidly switch between volume of displayed points.

I'm curious if you have any insight regarding the performance of this component. How well does it handle rendering several hundred pointers from a performance perspective? Does rendering a react component ( as opposed to a basic marker ) have additional performance repercussions? 

I would test this myself but am on a tight deadline and need to determine if this plugin fits my needs prior to spending dev time.

Thank you for any insight!

**Comment by avin** [comment]
@tconroy it's performance like in original leaflet. I have no performance problems with it showing ~200 div markers at once, but for more you should modify it to group markers or something else

**Comment by tconroy** [comment]
hey @avin, thanks for the reply.

Unfortunately I cannot use any sort of marker clustering.. each marker in-view needs to be independently visible. Haven't found a great solution for this yet, aside from canvas-based marker rendering but then adding interactivity with mouse/touch becomes trickier.. 

If you have any ideas I'm all ears :) 

Cheers.

**Comment by jeremiahrhall** [comment]
Hi @tconroy!

At OpenGov we found that, with a relatively recent laptop using a modern browser it was possible to handle approximately 2,500 items with this layer but, performance broke down quickly with more.

We have since moved to rendering the maps component in our reports with Mapbox GL JS. This uses WebGL to render the base layer and points. I am working on a blog post describing this transition but, in our application the Mapbox GL JS map handles around 100,000 points plotted at once.

If you need to stick with Leaflet and your markers have a fairly even geographic distribution, adding some logic to only render those markers within the viewport may help. I'd gladly review a PR with something like that.

Hope that helps!

**Comment by tconroy** [comment]
Thanks for the info, @jeremiahrhall!

Mapbox GL was my first choice -- unfortunately I'm stuck with leaflet for this project, but I look forward to reading your blog post for future projects.

Regarding your 2,500 point limit -- how did it perform on an average mobile device? Or did you not check that metric?

Thanks again for this great plugin. Always appreciate a solid OSS contribution.

Cheers
